In [1]:
%load_ext autoreload
%autoreload 2

In [21]:
import sys
import os
import copy
import numpy as np
from pathlib import Path
from omegaconf import OmegaConf
from tqdm import tqdm
import matplotlib.pyplot as plt
import torch
import torch.nn as nn

import time
from datetime import datetime

import pandas as pd
from IPython.display import display

# Add the project root to the path
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [4]:
root_dir = Path(module_path) / Path('aa_experiments')

In [10]:
exp_dir = root_dir / Path('cfo_final')
df_cfo = pd.read_csv(exp_dir / Path('eval_xtb_full.csv'))
df_cfo

,index,seed,step,graph_idx,valid,invalid_reason,simple_valid,simple_invalid_reason,qed,logp,...,atom_count_F,atom_count_P,atom_count_S,atom_count_Cl,atom_count_Br,atom_count_I,pred_reward,pred_constraint,true_reward,true_constraint
0,K,0,6,0,False,sanitize_fail,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,4.007875,-64.015160,4.894,-65.160135
1,K,0,6,1,False,disconnected,1.0,NaN,NaN,NaN,...,0,0,0,0,0,0,14.548645,-86.924767,3.582,-84.088228
2,K,0,6,2,False,sanitize_fail,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,4.053035,-71.270912,8.557,-73.142625
3,K,0,6,3,False,disconnected,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,6.281954,-76.666374,17.307,-75.006730
4,K,0,6,4,False,sanitize_fail,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,10.950938,-78.729843,12.268,-80.494196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,K,9,6,195,False,disconnected,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,5.547248,-77.878151,5.759,-74.665193
1996,K,9,6,196,False,disconnected,1.0,NaN,NaN,NaN,...,0,0,0,0,0,0,5.253828,-74.495644,3.841,-76.947194
1997,K,9,6,197,False,disconnected,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,11.179401,-88.030693,18.007,-86.470707
1998,K,9,6,198,False,disconnected,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,5.802702,-60.228931,3.158,-61.044086
1999,K,9,6,199,False,disconnected,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,9.218169,-68.613823,7.170,-67.941561

In [15]:
exp_dir = root_dir / Path('am_final')
df_am = pd.read_csv(exp_dir / Path('eval_xtb_full.csv'))
df_am

,index,seed,step,graph_idx,valid,invalid_reason,simple_valid,simple_invalid_reason,qed,logp,...,atom_count_F,atom_count_P,atom_count_S,atom_count_Cl,atom_count_Br,atom_count_I,pred_reward,pred_constraint,true_reward,true_constraint
0,K,0,1,0,False,sanitize_fail,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,4.344288,-65.128670,3.804,-66.979702
1,K,0,1,1,False,disconnected,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,10.868814,-75.801949,18.802,-77.475951
2,K,0,1,2,False,sanitize_fail,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,9.253829,-73.174126,13.086,-77.892098
3,K,0,1,3,False,sanitize_fail,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,8.796417,-78.943153,21.758,-85.418230
4,K,0,1,4,False,sanitize_fail,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,11.943373,-81.507393,16.594,-83.261934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,K,9,1,195,False,disconnected,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,6.525631,-73.348770,5.010,-77.754476
1996,K,9,1,196,False,disconnected,1.0,NaN,NaN,NaN,...,0,0,0,0,0,0,4.922368,-75.539490,4.057,-76.980958
1997,K,9,1,197,False,sanitize_fail,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,7.815562,-78.274940,6.346,-78.948122
1998,K,9,1,198,False,sanitize_fail,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,5.274614,-62.473118,20.039,-65.464898
1999,K,9,1,199,False,disconnected,0.0,sanitize_fail,NaN,NaN,...,0,0,0,0,0,0,9.391800,-67.373383,7.353,-68.075018

In [28]:
def last_step_stats_table(
    df: pd.DataFrame,
    *,
    step_col="step",
    seed_col="seed",
    sample_col="graph_idx",
    valid_col="valid",
    only_valid: bool = False,
    mode: str = "per_seed",   # "per_seed" | "pooled"
    exclude_cols=None,
    round_to: int = 3,
):
    """
    Statistics at the LAST step only.

    mode="per_seed":
        samples -> seed means -> CI across seeds

    mode="pooled":
        all samples treated equally -> CI across samples
    """

    if mode not in {"per_seed", "pooled"}:
        raise ValueError("mode must be 'per_seed' or 'pooled'")

    if exclude_cols is None:
        exclude_cols = {
            "index",
            seed_col,
            step_col,
            sample_col,
            "invalid_reason",
            "simple_invalid_reason",
            "murcko_scaffold_smiles",
        }

    # --- last step ---
    last_step = df[step_col].max()
    d = df[df[step_col] == last_step].copy()

    # --- optional valid-only filter ---
    if only_valid:
        d = d[d[valid_col] == True]

    # --- numeric columns INCLUDING valid ---
    numeric_cols = (
        d.select_dtypes(include=[np.number])
         .columns
         .difference(exclude_cols)
         .tolist()
    )

    rows = []

    if mode == "per_seed":
        # ---- per-seed means over samples ----
        per_seed = d.groupby(seed_col)[numeric_cols].mean()

        for col in numeric_cols:
            vals = per_seed[col].dropna()
            mean = vals.mean()
            sem = vals.sem()
            ci_lo = mean - 1.96 * sem
            ci_hi = mean + 1.96 * sem

            rows.append((col, mean, ci_lo, ci_hi))

    else:  # mode == "pooled"
        for col in numeric_cols:
            vals = d[col].dropna()
            mean = vals.mean()
            sem = vals.sem()
            ci_lo = mean - 1.96 * sem
            ci_hi = mean + 1.96 * sem

            rows.append((col, mean, ci_lo, ci_hi))

    # --- assemble table ---
    stats = pd.DataFrame(
        rows, columns=["metric", "mean", "ci_lo", "ci_hi"]
    )

    if round_to is not None:
        stats = stats.round(round_to)

    stats["mean ± 95% CI"] = (
        stats["mean"].astype(str)
        + " [" + stats["ci_lo"].astype(str)
        + ", " + stats["ci_hi"].astype(str) + "]"
    )

    display(stats)
    return stats

In [33]:
cfo_stats = last_step_stats_table(df_cfo, mode="per_seed")

                 metric     mean    ci_lo    ci_hi               mean ± 95% CI
0         atom_count_Br    0.001   -0.000    0.002         0.001 [-0.0, 0.002]
1          atom_count_C    1.086    0.884    1.287        1.086 [0.884, 1.287]
2         atom_count_Cl    0.002   -0.000    0.004         0.002 [-0.0, 0.004]
3          atom_count_F    0.005    0.001    0.009        0.005 [0.001, 0.009]
4          atom_count_H    1.386    1.095    1.678        1.386 [1.095, 1.678]
5          atom_count_I    0.000    0.000    0.000              0.0 [0.0, 0.0]
6          atom_count_N    0.397    0.307    0.487        0.397 [0.307, 0.487]
7          atom_count_O    0.348    0.268    0.428        0.348 [0.268, 0.428]
8          atom_count_P    0.000   -0.000    0.001           0.0 [-0.0, 0.001]
9          atom_count_S    0.015    0.008    0.021        0.015 [0.008, 0.021]
10                  hba    8.469    7.928    9.010         8.469 [7.928, 9.01]
11                  hbd    3.625    3.265    3.985        3.625 [3.265, 3.985]
12        lipinski_pass    0.702    0.616    0.788        0.702 [0.616, 0.788]
13  lipinski_violations    0.347    0.243    0.451        0.347 [0.243, 0.451]
14                 logp   -0.719   -1.163   -0.274     -0.719 [-1.163, -0.274]
15                   mw  366.360  358.626  374.095   366.36 [358.626, 374.095]
16              n_atoms      NaN      NaN      NaN              nan [nan, nan]
17      pred_constraint  -81.837  -82.210  -81.464   -81.837 [-82.21, -81.464]
18          pred_reward    8.489    8.382    8.595        8.489 [8.382, 8.595]
19                  qed    0.355    0.318    0.391        0.355 [0.318, 0.391]
20         simple_valid    0.130    0.110    0.151          0.13 [0.11, 0.151]
21      true_constraint  -81.038  -81.793  -80.284  -81.038 [-81.793, -80.284]
22          true_reward   10.129    9.934   10.324      10.129 [9.934, 10.324]

In [ ]:
am_stats = last_step_stats_table(df_am, mode="per_seed")

                 metric     mean    ci_lo    ci_hi               mean ± 95% CI
0         atom_count_Br    0.002    0.000    0.003          0.002 [0.0, 0.003]
1          atom_count_C    0.919    0.635    1.202        0.919 [0.635, 1.202]
2         atom_count_Cl    0.002    0.000    0.004          0.002 [0.0, 0.004]
3          atom_count_F    0.006    0.001    0.010         0.006 [0.001, 0.01]
4          atom_count_H    1.190    0.834    1.545         1.19 [0.834, 1.545]
5          atom_count_I    0.000    0.000    0.000              0.0 [0.0, 0.0]
6          atom_count_N    0.397    0.270    0.524         0.397 [0.27, 0.524]
7          atom_count_O    0.262    0.171    0.354        0.262 [0.171, 0.354]
8          atom_count_P    0.000   -0.000    0.001           0.0 [-0.0, 0.001]
9          atom_count_S    0.013    0.007    0.019        0.013 [0.007, 0.019]
10                  hba    8.357    7.608    9.105        8.357 [7.608, 9.105]
11                  hbd    3.958    3.443    4.473        3.958 [3.443, 4.473]
12        lipinski_pass    0.654    0.588    0.720         0.654 [0.588, 0.72]
13  lipinski_violations    0.437    0.316    0.559        0.437 [0.316, 0.559]
14                 logp   -1.126   -1.747   -0.505     -1.126 [-1.747, -0.505]
15                   mw  363.620  356.618  370.622   363.62 [356.618, 370.622]
16              n_atoms      NaN      NaN      NaN              nan [nan, nan]
17      pred_constraint  -78.652  -79.098  -78.206  -78.652 [-79.098, -78.206]
18          pred_reward    8.241    8.084    8.397        8.241 [8.084, 8.397]
19                  qed    0.352    0.304    0.399        0.352 [0.304, 0.399]
20         simple_valid    0.086    0.068    0.104        0.086 [0.068, 0.104]
21      true_constraint  -79.870  -80.715  -79.026   -79.87 [-80.715, -79.026]
22          true_reward   10.241    9.922   10.561      10.241 [9.922, 10.561]

In [ ]:
cfo_stats_pooled = last_step_stats_table(df_cfo, mode="pooled")

                 metric     mean    ci_lo    ci_hi               mean ± 95% CI
0         atom_count_Br    0.001   -0.000    0.002         0.001 [-0.0, 0.002]
1          atom_count_C    1.086    0.913    1.258        1.086 [0.913, 1.258]
2         atom_count_Cl    0.002    0.000    0.004          0.002 [0.0, 0.004]
3          atom_count_F    0.005    0.000    0.010           0.005 [0.0, 0.01]
4          atom_count_H    1.386    1.166    1.607        1.386 [1.166, 1.607]
5          atom_count_I    0.000    0.000    0.000              0.0 [0.0, 0.0]
6          atom_count_N    0.397    0.330    0.464         0.397 [0.33, 0.464]
7          atom_count_O    0.348    0.288    0.408        0.348 [0.288, 0.408]
8          atom_count_P    0.000   -0.000    0.001           0.0 [-0.0, 0.001]
9          atom_count_S    0.014    0.009    0.020         0.014 [0.009, 0.02]
10                  hba    8.521    8.129    8.912        8.521 [8.129, 8.912]
11                  hbd    3.736    3.414    4.058        3.736 [3.414, 4.058]
12        lipinski_pass    0.681    0.604    0.757        0.681 [0.604, 0.757]
13  lipinski_violations    0.375    0.279    0.471        0.375 [0.279, 0.471]
14                 logp   -0.814   -1.190   -0.438      -0.814 [-1.19, -0.438]
15                   mw  365.142  359.208  371.076  365.142 [359.208, 371.076]
16              n_atoms      NaN      NaN      NaN              nan [nan, nan]
17      pred_constraint  -81.837  -82.210  -81.464   -81.837 [-82.21, -81.464]
18          pred_reward    8.489    8.348    8.630         8.489 [8.348, 8.63]
19                  qed    0.346    0.314    0.379        0.346 [0.314, 0.379]
20         simple_valid    0.130    0.116    0.145         0.13 [0.116, 0.145]
21      true_constraint  -81.039  -81.597  -80.480   -81.039 [-81.597, -80.48]
22          true_reward   10.129    9.895   10.363      10.129 [9.895, 10.363]

In [ ]:
am_stats_pooled = last_step_stats_table(df_am, mode="pooled")

                 metric     mean    ci_lo    ci_hi               mean ± 95% CI
0         atom_count_Br    0.002   -0.000    0.003         0.002 [-0.0, 0.003]
1          atom_count_C    0.918    0.760    1.077         0.918 [0.76, 1.077]
2         atom_count_Cl    0.002    0.000    0.004          0.002 [0.0, 0.004]
3          atom_count_F    0.006    0.001    0.010         0.006 [0.001, 0.01]
4          atom_count_H    1.190    0.985    1.394         1.19 [0.985, 1.394]
5          atom_count_I    0.000    0.000    0.000              0.0 [0.0, 0.0]
6          atom_count_N    0.397    0.324    0.470         0.397 [0.324, 0.47]
7          atom_count_O    0.262    0.212    0.313        0.262 [0.212, 0.313]
8          atom_count_P    0.000   -0.000    0.001           0.0 [-0.0, 0.001]
9          atom_count_S    0.013    0.008    0.018        0.013 [0.008, 0.018]
10                  hba    8.581    8.118    9.043        8.581 [8.118, 9.043]
11                  hbd    3.863    3.521    4.205        3.863 [3.521, 4.205]
12        lipinski_pass    0.653    0.569    0.737        0.653 [0.569, 0.737]
13  lipinski_violations    0.435    0.321    0.550         0.435 [0.321, 0.55]
14                 logp   -1.171   -1.603   -0.739     -1.171 [-1.603, -0.739]
15                   mw  366.439  359.867  373.012  366.439 [359.867, 373.012]
16              n_atoms      NaN      NaN      NaN              nan [nan, nan]
17      pred_constraint  -78.652  -78.967  -78.338  -78.652 [-78.967, -78.338]
18          pred_reward    8.241    8.108    8.373        8.241 [8.108, 8.373]
19                  qed    0.351    0.315    0.387        0.351 [0.315, 0.387]
20         simple_valid    0.086    0.074    0.098        0.086 [0.074, 0.098]
21      true_constraint  -79.871  -80.432  -79.310   -79.871 [-80.432, -79.31]
22          true_reward   10.241   10.002   10.480      10.241 [10.002, 10.48]

In [34]:
def last_step_stats_table(
    df: pd.DataFrame,
    *,
    step_col="step",
    seed_col="seed",
    sample_col="graph_idx",
    valid_col="valid",
    simple_valid_col="simple_valid",
    only_valid: bool = False,     # applies ONLY to non-validity metrics
    mode: str = "per_seed",       # "per_seed" | "pooled"
    exclude_cols=None,
    round_to: int = 3,
):
    if mode not in {"per_seed", "pooled"}:
        raise ValueError("mode must be 'per_seed' or 'pooled'")

    if exclude_cols is None:
        exclude_cols = {
            "index", seed_col, step_col, sample_col,
            "invalid_reason", "simple_invalid_reason",
            "murcko_scaffold_smiles",
        }

    # --- last step slice ---
    last_step = df[step_col].max()
    d_last = df[df[step_col] == last_step].copy()

    # -------------------------
    # 1) VALIDITY FRACTIONS (always computed on ALL last-step samples)
    # -------------------------
    def _fraction_stats_from_bool_col(d, colname, out_metric_name):
        if colname not in d.columns:
            return None

        # Ensure boolean-ish -> float in {0,1}
        vals = d[colname].astype(float)

        if mode == "per_seed":
            per_seed_frac = vals.groupby(d[seed_col]).mean().dropna()
            mean = per_seed_frac.mean()
            sem = per_seed_frac.sem()
        else:  # pooled
            vals2 = vals.dropna()
            mean = vals2.mean()
            sem = vals2.sem()

        ci_lo = mean - 1.96 * sem
        ci_hi = mean + 1.96 * sem
        return (out_metric_name, mean, ci_lo, ci_hi)

    rows = []
    r = _fraction_stats_from_bool_col(d_last, valid_col, "valid_fraction")
    if r is not None:
        rows.append(r)

    r = _fraction_stats_from_bool_col(d_last, simple_valid_col, "simple_valid_fraction")
    if r is not None:
        rows.append(r)

    # Some helpful counts for sanity checking
    n_seeds = d_last[seed_col].nunique()
    n_samples_total = len(d_last)
    n_valid_total = int(d_last[valid_col].sum()) if valid_col in d_last.columns else None

    # -------------------------
    # 2) OTHER NUMERIC METRICS (optionally filter to only_valid)
    # -------------------------
    d_metrics = d_last.copy()
    if only_valid:
        d_metrics = d_metrics[d_metrics[valid_col] == True].copy()

    numeric_cols = (
        d_metrics.select_dtypes(include=[np.number])
        .columns.difference(exclude_cols)
        .tolist()
    )

    # Remove validity columns from numeric list to avoid duplicates / confusion
    for c in [valid_col, simple_valid_col]:
        if c in numeric_cols:
            numeric_cols.remove(c)

    if mode == "per_seed":
        per_seed = d_metrics.groupby(seed_col)[numeric_cols].mean()
        for col in numeric_cols:
            vals = per_seed[col].dropna()
            mean = vals.mean()
            sem = vals.sem()
            rows.append((col, mean, mean - 1.96 * sem, mean + 1.96 * sem))
    else:  # pooled
        for col in numeric_cols:
            vals = d_metrics[col].dropna()
            mean = vals.mean()
            sem = vals.sem()
            rows.append((col, mean, mean - 1.96 * sem, mean + 1.96 * sem))

    # -------------------------
    # 3) Assemble & display
    # -------------------------
    stats = pd.DataFrame(rows, columns=["metric", "mean", "ci_lo", "ci_hi"])

    if round_to is not None:
        stats[["mean", "ci_lo", "ci_hi"]] = stats[["mean", "ci_lo", "ci_hi"]].round(round_to)

    stats["mean ± 95% CI"] = (
        stats["mean"].astype(str)
        + " [" + stats["ci_lo"].astype(str)
        + ", " + stats["ci_hi"].astype(str) + "]"
    )

    # Put validity fractions at top
    validity_order = ["valid_fraction", "simple_valid_fraction"]
    stats["__rank"] = stats["metric"].apply(lambda m: validity_order.index(m) if m in validity_order else 999)
    stats = stats.sort_values(["__rank", "metric"]).drop(columns="__rank").reset_index(drop=True)

    # Show counts header + table
    print(f"Last step = {last_step} | mode = {mode} | only_valid(metrics) = {only_valid}")
    print(f"n_seeds = {n_seeds} | n_samples_total = {n_samples_total}" + (f" | n_valid_total = {n_valid_total}" if n_valid_total is not None else ""))
    display(stats)

    return stats

In [35]:
print("\nCFO Stats:")
cfo_stats = last_step_stats_table(df_cfo, mode="per_seed")
print("\nAM Stats:")
am_stats = last_step_stats_table(df_am, mode="per_seed")
print("\nCFO Pooled Stats:")
cfo_stats_pooled = last_step_stats_table(df_cfo, mode="pooled")
print("\nAM Pooled Stats:")
am_stats_pooled = last_step_stats_table(df_am, mode="pooled")

CFO Stats:
Last step = 6 | mode = per_seed | only_valid(metrics) = False
n_seeds = 10 | n_samples_total = 2000 | n_valid_total = 144

,metric,mean,ci_lo,ci_hi,mean ± 95% CI
0,valid_fraction,0.072,0.057,0.087,"0.072 [0.057, 0.087]"
1,simple_valid_fraction,0.130,0.110,0.151,"0.13 [0.11, 0.151]"
2,atom_count_Br,0.001,-0.000,0.002,"0.001 [-0.0, 0.002]"
3,atom_count_C,1.086,0.884,1.287,"1.086 [0.884, 1.287]"
4,atom_count_Cl,0.002,-0.000,0.004,"0.002 [-0.0, 0.004]"
5,atom_count_F,0.005,0.001,0.009,"0.005 [0.001, 0.009]"
6,atom_count_H,1.386,1.095,1.678,"1.386 [1.095, 1.678]"
7,atom_count_I,0.000,0.000,0.000,"0.0 [0.0, 0.0]"
8,atom_count_N,0.397,0.307,0.487,"0.397 [0.307, 0.487]"
9,atom_count_O,0.348,0.268,0.428,"0.348 [0.268, 0.428]"
10,atom_count_P,0.000,-0.000,0.001,"0.0 [-0.0, 0.001]"
11,atom_count_S,0.015,0.008,0.021,"0.015 [0.008, 0.021]"
12,hba,8.469,7.928,9.010,"8.469 [7.928, 9.01]"
13,hbd,3.625,3.265,3.985,"3.625 [3.265, 3.985]"
14,lipinski_pass,0.702,0.616,0.788,"0.702 [0.616, 0.788]"
15,lipinski_violations,0.347,0.243,0.451,"0.347 [0.243, 0.451]"
16,logp,-0.719,-1.163,-0.274,"-0.719 [-1.163, -0.274]"
17,mw,366.360,358.626,374.095,"366.36 [358.626, 374.095]"
18,n_atoms,NaN,NaN,NaN,"nan [nan, nan]"
19,pred_constraint,-81.837,-82.210,-81.464,"-81.837 [-82.21, -81.464]"
20,pred_reward,8.489,8.382,8.595,"8.489 [8.382, 8.595]"
21,qed,0.355,0.318,0.391,"0.355 [0.318, 0.391]"
22,true_constraint,-81.038,-81.793,-80.284,"-81.038 [-81.793, -80.284]"
23,true_reward,10.129,9.934,10.324,"10.129 [9.934, 10.324]"

AM Stats:
Last step = 1 | mode = per_seed | only_valid(metrics) = False
n_seeds = 10 | n_samples_total = 2000 | n_valid_total = 124

,metric,mean,ci_lo,ci_hi,mean ± 95% CI
0,valid_fraction,0.062,0.043,0.081,"0.062 [0.043, 0.081]"
1,simple_valid_fraction,0.086,0.068,0.104,"0.086 [0.068, 0.104]"
2,atom_count_Br,0.002,0.000,0.003,"0.002 [0.0, 0.003]"
3,atom_count_C,0.919,0.635,1.202,"0.919 [0.635, 1.202]"
4,atom_count_Cl,0.002,0.000,0.004,"0.002 [0.0, 0.004]"
5,atom_count_F,0.006,0.001,0.010,"0.006 [0.001, 0.01]"
6,atom_count_H,1.190,0.834,1.545,"1.19 [0.834, 1.545]"
7,atom_count_I,0.000,0.000,0.000,"0.0 [0.0, 0.0]"
8,atom_count_N,0.397,0.270,0.524,"0.397 [0.27, 0.524]"
9,atom_count_O,0.262,0.171,0.354,"0.262 [0.171, 0.354]"
10,atom_count_P,0.000,-0.000,0.001,"0.0 [-0.0, 0.001]"
11,atom_count_S,0.013,0.007,0.019,"0.013 [0.007, 0.019]"
12,hba,8.357,7.608,9.105,"8.357 [7.608, 9.105]"
13,hbd,3.958,3.443,4.473,"3.958 [3.443, 4.473]"
14,lipinski_pass,0.654,0.588,0.720,"0.654 [0.588, 0.72]"
15,lipinski_violations,0.437,0.316,0.559,"0.437 [0.316, 0.559]"
16,logp,-1.126,-1.747,-0.505,"-1.126 [-1.747, -0.505]"
17,mw,363.620,356.618,370.622,"363.62 [356.618, 370.622]"
18,n_atoms,NaN,NaN,NaN,"nan [nan, nan]"
19,pred_constraint,-78.652,-79.098,-78.206,"-78.652 [-79.098, -78.206]"
20,pred_reward,8.241,8.084,8.397,"8.241 [8.084, 8.397]"
21,qed,0.352,0.304,0.399,"0.352 [0.304, 0.399]"
22,true_constraint,-79.870,-80.715,-79.026,"-79.87 [-80.715, -79.026]"
23,true_reward,10.241,9.922,10.561,"10.241 [9.922, 10.561]"

CFO Pooled Stats:
Last step = 6 | mode = pooled | only_valid(metrics) = False
n_seeds = 10 | n_samples_total = 2000 | n_valid_total = 144

,metric,mean,ci_lo,ci_hi,mean ± 95% CI
0,valid_fraction,0.072,0.061,0.083,"0.072 [0.061, 0.083]"
1,simple_valid_fraction,0.130,0.116,0.145,"0.13 [0.116, 0.145]"
2,atom_count_Br,0.001,-0.000,0.002,"0.001 [-0.0, 0.002]"
3,atom_count_C,1.086,0.913,1.258,"1.086 [0.913, 1.258]"
4,atom_count_Cl,0.002,0.000,0.004,"0.002 [0.0, 0.004]"
5,atom_count_F,0.005,0.000,0.010,"0.005 [0.0, 0.01]"
6,atom_count_H,1.386,1.166,1.607,"1.386 [1.166, 1.607]"
7,atom_count_I,0.000,0.000,0.000,"0.0 [0.0, 0.0]"
8,atom_count_N,0.397,0.330,0.464,"0.397 [0.33, 0.464]"
9,atom_count_O,0.348,0.288,0.408,"0.348 [0.288, 0.408]"
10,atom_count_P,0.000,-0.000,0.001,"0.0 [-0.0, 0.001]"
11,atom_count_S,0.014,0.009,0.020,"0.014 [0.009, 0.02]"
12,hba,8.521,8.129,8.912,"8.521 [8.129, 8.912]"
13,hbd,3.736,3.414,4.058,"3.736 [3.414, 4.058]"
14,lipinski_pass,0.681,0.604,0.757,"0.681 [0.604, 0.757]"
15,lipinski_violations,0.375,0.279,0.471,"0.375 [0.279, 0.471]"
16,logp,-0.814,-1.190,-0.438,"-0.814 [-1.19, -0.438]"
17,mw,365.142,359.208,371.076,"365.142 [359.208, 371.076]"
18,n_atoms,NaN,NaN,NaN,"nan [nan, nan]"
19,pred_constraint,-81.837,-82.210,-81.464,"-81.837 [-82.21, -81.464]"
20,pred_reward,8.489,8.348,8.630,"8.489 [8.348, 8.63]"
21,qed,0.346,0.314,0.379,"0.346 [0.314, 0.379]"
22,true_constraint,-81.039,-81.597,-80.480,"-81.039 [-81.597, -80.48]"
23,true_reward,10.129,9.895,10.363,"10.129 [9.895, 10.363]"

AM Pooled Stats:
Last step = 1 | mode = pooled | only_valid(metrics) = False
n_seeds = 10 | n_samples_total = 2000 | n_valid_total = 124

,metric,mean,ci_lo,ci_hi,mean ± 95% CI
0,valid_fraction,0.062,0.051,0.073,"0.062 [0.051, 0.073]"
1,simple_valid_fraction,0.086,0.074,0.098,"0.086 [0.074, 0.098]"
2,atom_count_Br,0.002,-0.000,0.003,"0.002 [-0.0, 0.003]"
3,atom_count_C,0.918,0.760,1.077,"0.918 [0.76, 1.077]"
4,atom_count_Cl,0.002,0.000,0.004,"0.002 [0.0, 0.004]"
5,atom_count_F,0.006,0.001,0.010,"0.006 [0.001, 0.01]"
6,atom_count_H,1.190,0.985,1.394,"1.19 [0.985, 1.394]"
7,atom_count_I,0.000,0.000,0.000,"0.0 [0.0, 0.0]"
8,atom_count_N,0.397,0.324,0.470,"0.397 [0.324, 0.47]"
9,atom_count_O,0.262,0.212,0.313,"0.262 [0.212, 0.313]"
10,atom_count_P,0.000,-0.000,0.001,"0.0 [-0.0, 0.001]"
11,atom_count_S,0.013,0.008,0.018,"0.013 [0.008, 0.018]"
12,hba,8.581,8.118,9.043,"8.581 [8.118, 9.043]"
13,hbd,3.863,3.521,4.205,"3.863 [3.521, 4.205]"
14,lipinski_pass,0.653,0.569,0.737,"0.653 [0.569, 0.737]"
15,lipinski_violations,0.435,0.321,0.550,"0.435 [0.321, 0.55]"
16,logp,-1.171,-1.603,-0.739,"-1.171 [-1.603, -0.739]"
17,mw,366.439,359.867,373.012,"366.439 [359.867, 373.012]"
18,n_atoms,NaN,NaN,NaN,"nan [nan, nan]"
19,pred_constraint,-78.652,-78.967,-78.338,"-78.652 [-78.967, -78.338]"
20,pred_reward,8.241,8.108,8.373,"8.241 [8.108, 8.373]"
21,qed,0.351,0.315,0.387,"0.351 [0.315, 0.387]"
22,true_constraint,-79.871,-80.432,-79.310,"-79.871 [-80.432, -79.31]"
23,true_reward,10.241,10.002,10.480,"10.241 [10.002, 10.48]"